name: Build and Deploy Sphinx Docs

on:
  push:
    branches:
      - main           # Main branch for stable releases
      - development    # Development branch for in-progress changes
    tags:
      - 'v*'       # Matches any tag prefixed with 'v', e.g., v1.0, v2.1

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
        contents: write

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Determine the target branch for deployment
        id: deployment_target
        run: |
          if [[ $GITHUB_REF == refs/heads/main ]]; then
            echo "TARGET_BRANCH=gh-pages" >> $GITHUB_ENV
          elif [[ $GITHUB_REF == refs/heads/develop ]]; then
            echo "TARGET_BRANCH=gh-pages-dev" >> $GITHUB_ENV
          elif [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "TARGET_BRANCH=gh-pages-versioned" >> $GITHUB_ENV
          else
            echo "TARGET_BRANCH=gh-pages" >> $GITHUB_ENV
          fi

      - name: Build Sphinx documentation
        run: |
          make html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_build/html
          destination_branch: ${{ env.TARGET_BRANCH }}
